version: '3.8'

services:
  melembraai-backend:
    build: .
    environment:
      - PORT=3001
      - NODE_ENV=development
      - JWT_SECRET=melembraai_secret_key_2025
      - JWT_EXPIRES_IN=7d
      - DATABASE_URL=file:./database/dev.db
    volumes:
      - .:/app
      - db-data:/app/database
    ports:
      - "3001:3001"
    command: sh -c "npx prisma migrate deploy && npx prisma generate && npx ts-node-dev --respawn --transpile-only src/server.ts"

volumes:
  db-data:
