import type { Metadata } from "next";
import favicon from "./favicon.ico";
import { Geist } from "next/font/google";
import "./globals.css";


const outfit= Geist({
  variable: "--font-outfit",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Minha Conta",
  description: "Generated by create next app",
  icons: {
    icon: favicon.src,
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${outfit.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
